server: 
 port: 8089

nacos:  
  config: 
    server-addr: 192.168.1.52:8848
    
#spring: 
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.xx:3306/test-spring-boot
#    username: root
#    password: root
#
#mybatis:
#  mapper-locations: classpath:*Mapper.xml