server:
  port: 8081
  
spring:
  application:
    name: api-gateway-01
    
  cloud:
    gateway:
      discovery: 
        locator: 
              #开启以服务id去注册中心上获取转发地址
            enabled: true
            
        #路由策略
      routes:
        - id: gateway-service1
            #转发到目的地址 http://realUrl.userApi001.com
          uri: http://realUrl.userApi001.com
          #uri: https://www.baidu.com/
            #匹配规则
          predicates:
            - Path=/userApi/**
            ## 最终拦截效果 http://localhost:8081/userApi  转发到 http://realUrl.userApi001.com