
package testWebserviceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebserviceDemo", targetNamespace = "http://testWebserviceServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebserviceDemo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloToYou", targetNamespace = "http://testWebserviceServer/", className = "client.HelloToYou")
    @ResponseWrapper(localName = "helloToYouResponse", targetNamespace = "http://testWebserviceServer/", className = "client.HelloToYouResponse")
    @Action(input = "http://testWebserviceServer/WebserviceDemo/helloToYouRequest", output = "http://testWebserviceServer/WebserviceDemo/helloToYouResponse")
    public String helloToYou(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://testWebserviceServer/", className = "client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://testWebserviceServer/", className = "client.HelloResponse")
    @Action(input = "http://testWebserviceServer/WebserviceDemo/helloRequest", output = "http://testWebserviceServer/WebserviceDemo/helloResponse")
    public String hello();

}
